// ─────────────────────────────────────────────────────────────────────────
// THE COLLECTION
// ─────────────────────────────────────────────────────────────────────────
// This is the only file you need to edit to populate your gallery.
//
// 1. Drop your image files into:  public/art/
// 2. Add one entry below per artwork, in the order you want them to appear
//    as you swipe through the gallery (like rooms in a museum).
// 3. `src` should be the filename only — it's resolved against /art/.
//
// Fields:
//   id       — unique short string, used as a React key (e.g. "001")
//   src      — filename inside public/art/, e.g. "midnight-orchard.jpg"
//   title    — artwork title, shown on the wall placard
//   year     — year created, e.g. "2024" (string, so "c. 2023" also works)
//   medium   — e.g. "Oil on canvas", "Digital", "Charcoal on paper"
//   dimensions — optional, e.g. "60 × 80 cm"
//   note     — optional short curator's note / artist statement (1-2 lines)
//
// Leave the array empty (as it is now) and the gallery will show a friendly
// "empty room" state until you add your first piece.
// ─────────────────────────────────────────────────────────────────────────

export const artworks = [
  {
     id: '001',
     src: '1.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '002',
     src: '2.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '003',
     src: '3.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '004',
     src: '4.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '005',
     src: '5.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '006',
     src: '6.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '007',
     src: '7.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '008',
     src: '8.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '009',
     src: '9.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '0010',
     src: '10.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '0011',
     src: '11.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '012',
     src: '12.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '013',
     src: '13.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '014',
     src: '14.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '016',
     src: '16.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '017',
     src: '17.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '018',
     src: '18.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '019',
     src: '19.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '020',
     src: '20.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '021',
     src: '21.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '022',
     src: '22.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '023',
     src: '23.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '024',
     src: '24.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '025',
     src: '25.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '026',
     src: '26.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '027',
     src: '27.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '028',
     src: '28.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '029',
     src: '29.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '030',
     src: '30.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '031',
     src: '31.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '032',
     src: '32.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '033',
     src: '33.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '034',
     src: '34.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
   {
     id: '035',
     src: '35.jpeg',
     title: 'Midnight Orchard',
     year: '2024',
     medium: 'Oil on canvas',
     dimensions: '60 × 80 cm',
     note: 'Painted over three nights in late autumn.',
   },
]

export const artistInfo = {
  name: 'Nandini',
  tagline: 'A collection of recent works',
  photo: 'profile.png',
}
